export const languageMap = {
  "1c": [],
  "abnf": [],
  "accesslog": [],
  "actionscript": ["as"],
  "ada": ["ada", "adb", "ads"],
  "angelscript": ["angelscript"],
  "apache": ["apache"],
  "applescript": ["app"],
  "arcade": ["arcade"],
  "arduino": ["ino"],
  "armasm": ["s"],
  "asciidoc": ["adoc"],
  "aspectj": ["aj"],
  "autohotkey": ["ahk"],
  "autoit": ["au3"],
  "avrasm": ["s"],
  "awk": ["awk"],
  "axapta": ["ax"],
  "bash": ["sh", "bash"],
  "basic": ["bas"],
  "bnf": ["bnf"],
  "brainfuck": ["b", "bf"],
  "c": ["c"],
  "cal": ["cal"],
  "capnproto": ["capnp"],
  "ceylon": ["ceylon"],
  "clean": ["icl", "dcl"],
  "clojure-repl": [],
  "clojure": ["clj", "cljc", "cljx", "cljs"],
  "cmake": ["CMakeLists.txt", "cmake"],
  "coffeescript": ["coffee"],
  "coq": ["v"],
  "cos": ["cls", "int"],
  "cpp": ["cpp", "cc", "h", "C", "H", "hpp"],
  "crmsh": ["crm"],
  "crystal": ["cr"],
  "csharp": ["cs"],
  "csp": ["csp"],
  "css": ["css"],
  "d": ["d"],
  "dart": ["dart"],
  "delphi": ["dpr", "dpk", "pas"],
  "diff": ["diff", "patch"],
  "django": ["djhtml"],
  "dns": ["zone", "bind"],
  "dockerfile": ["Dockerfile"],
  "dos": ["bat", "cmd"],
  "dsconfig": ["dsconfig"],
  "dts": ["dts"],
  "dust": ["dust"],
  "ebnf": ["ebnf"],
  "elixir": ["ex", "exs"],
  "elm": ["elm"],
  "erb": ["erb"],
  "erlang-repl": [],
  "erlang": ["erl", "hrl"],
  "excel": ["xls", "xlsx"],
  "fix": ["fix"],
  "flix": ["flix"],
  "fortran": ["f", "for", "f90", "f95"],
  "fsharp": ["fs", "fsi"],
  "gams": ["gms"],
  "gauss": ["gss", "gms"],
  "gcode": ["gcode"],
  "gherkin": ["feature"],
  "glsl": ["vert", "frag", "geom"],
  "gml": ["gml"],
  "go": ["go"],
  "golo": ["golo"],
  "gradle": ["gradle"],
  "graphql": ["graphql", "gql"],
  "groovy": ["groovy"],
  "haml": ["haml"],
  "handlebars": ["hbs"],
  "haskell": ["hs"],
  "haxe": ["hx"],
  "hsp": ["hsp"],
  "http": ["http"],
  "hy": ["hy"],
  "inform7": ["ni", "n"],
  "ini": ["ini"],
  "irpf90": ["f", "f90"],
  "isbl": ["isbl"],
  "java": ["java"],
  "javascript": ["js"],
  "jboss-cli": ["cli"],
  "json": ["json", "json5"],
  "julia-repl": [],
  "julia": ["jl"],
  "kotlin": ["kt", "kts", "ktm"],
  "lasso": ["lasso", "lassoapp"],
  "latex": ["tex"],
  "ldif": ["ldif"],
  "leaf": ["leaf"],
  "less": ["less"],
  "lisp": ["lisp"],
  "livecodeserver": ["lc", "irev"],
  "livescript": ["ls"],
  "llvm": ["ll"],
  "lsl": ["lsl"],
  "lua": ["lua"],
  "makefile": ["Makefile"],
  "markdown": ["md", "markdown"],
  "mathematica": ["nb"],
  "matlab": ["m"],
  "maxima": ["mac", "mc"],
  "mel": ["mel"],
  "mercury": ["m", "mh", "pro"],
  "mipsasm": ["s"],
  "mizar": ["miz"],
  "mojolicious": ["ep"],
  "monkey": ["monkey"],
  "moonscript": ["moon"],
  "n1ql": ["n1ql"],
  "nestedtext": ["nt"],
  "nginx": ["nginx.conf"],
  "nim": ["nim"],
  "nix": ["nix"],
  "node-repl": [],
  "nsis": ["nsi", "nsh"],
  "objectivec": ["m", "mm"],
  "ocaml": ["ml", "mli"],
  "openscad": ["scad"],
  "oxygene": ["oxygene"],
  "parser3": ["parser3"],
  "perl": ["pl", "pm"],
  "pf": ["pf"],
  "pgsql": ["pgsql"],
  "php-template": ["phtml"],
  "php": ["php", "php5", "php7", "php8"],
  "plaintext": ["txt"],
  "pony": ["pony"],
  "powershell": ["ps1", "psm1"],
  "processing": ["pde"],
  "profile": [],
  "prolog": ["pl", "pro", "P"],
  "properties": ["properties"],
  "protobuf": ["proto"],
  "puppet": ["pp"],
  "purebasic": ["pb", "pbi"],
  "python-repl": [],
  "python": ["py"],
  "q": ["q"],
  "qml": ["qml"],
  "r": ["R"],
  "reasonml": ["re", "rei"],
  "rib": ["rib"],
  "roboconf": ["rbcf"],
  "routeros": ["rsc"],
  "rsl": ["rsl"],
  "ruby": ["rb"],
  "ruleslanguage": ["ruleslanguage"],
  "rust": ["rs"],
  "sas": ["sas"],
  "scala": ["scala"],
  "scheme": ["scm"],
  "scilab": ["sci"],
  "scss": ["scss"],
  "shell": ["sh", "bash", "dash", "ksh", "csh", "tcsh", "zsh", "fish"],
  "smali": ["smali"],
  "smalltalk": ["st"],
  "sml": ["sml", "sig", "fun"],
  "sqf": ["sqf"],
  "sql": ["sql"],
  "stan": ["stan"],
  "stata": ["do", "ado"],
  "step21": ["stp"],
  "stylus": ["styl"],
  "subunit": ["subunit"],
  "swift": ["swift"],
  "taggerscript": ["taggerscript"],
  "tap": ["tap"],
  "tcl": ["tcl"],
  "thrift": ["thrift"],
  "tp": ["tp"],
  "twig": ["twig"],
  "typescript": ["ts"],
  "vala": ["vala"],
  "vbnet": ["vb"],
  "vbscript-html": ["vbshtml"],
  "vbscript": ["vbs"],
  "verilog": ["v"],
  "vhdl": ["vhdl"],
  "vim": ["vim"],
  "wasm": [],
  "wren": ["wren"],
  "x86asm": ["s"],
  "xl": ["xl", "ilst"],
  "xml": ["xml", "svg", "dtd"],
  "xquery": ["xy", "xquery"],
  "yaml": ["yaml", "yml"],
  "zephir": ["zep"],
};
